---
title: "Code for generating the tables and figures"
  compositions'
output:
  html_notebook:
    toc: yes
  html_document:
    toc: yes
---

 
 
 
###Export LaTex style tables 

This code serves to export in LaTex style the table summary. The code is developed by: 

Hlavac, Marek (2015). stargazer: Well-Formatted Regression and Summary Statistics
  Tables. R package version 5.2. http://CRAN.R-project.org/package=stargazer

```{r}
if (!require("stargazer")) {
   install.packages("gplots", dependencies = TRUE)
   library(gplots)
   }
library("stargazer")
```

Copy and paste this code in te tex file. 

```{r}
stargazer(sum_table(GR_GLO[,-c(1:3,13)]), title = "GR-GLO summary table")
stargazer(MVC_GR_GLO, title = "MVC of GR-GLO")
```

```{r}
stargazer(sum_table(GR_NF[,-c(1:3,13)]), title = "GR-NF summary table")
stargazer(MVC_GR_NF, title = "MVC of GR-NF")
```
MVC_GR_WA
```{r}
stargazer(sum_table(GR_NF[,-c(1:3,13)]), title = "GR-WA summary table")
stargazer(MVC_GR_WA, title = "MVC of GR-WA")
```