install.packages("archdata")
install.packages("rmarkdown")
install.packages("compositions")
install.packages("devEMF")
install.packages("ggthemes")
install.packages("devtools")
install.packages("plotrix")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("dendextend")
install.packages("stargaze")
library(devtools)
install_github("vqv/ggbiplot")
devtools::install_github("richardjtelford/ggbiplot", ref = "experimental")

